baseURL = "https://blog.victorprouff.fr"
languageCode = "fr-fr"
theme = "anatole"
paginate = 25
canonifyurls = true
DefaultContentLanguage = "fr"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Google Analytics
#googleAnalytics = "UA-123-45"
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

## Menu items
[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  # [[menu.main]]
  # name = "Boïte à outils"
  # identifier = "tools"
  # weight = 300
  # url = "/tools/"