
title = "Victor Prouff"
author = "Victor Prouff"
#copyright = "2020-2021"
description = "Développeur / Photographe"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css"]

# example ["js/custom.js"]
customJs = [] 
mainSections = ["posts"]
# images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "02/01/2006"
indexDateFormat = "02/01/2006"
listDateFormat = "02/01/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3


reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fa-brands' when brand icons, use 'fas' when standard solid icons.
#  [[params.socialIcons]]
#  icon = "fa-linkedin"
#  title = "Linkedin"
#  url = "https://de.linkedin.com/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/victorprouff/"

#  [[params.socialIcons]]
#  icon = "fa-instagram"
#  title = "instagram"
#  url = "https://www.instagram.com/"

  [[params.socialIcons]]
  icon = "fa-envelope"
  title = "e-mail"
  url = "mailto:contact@victorprouff.fr"

[mermaid]
# enable = true