baseURL = "/"
languageCode = "fr-fr"
theme = "anatole"
paginate = 7
canonifyurls = true
DefaultContentLanguage = "fr"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
  title = "Victor Prouff"
  author = "Victor Prouff"
  description = "Développeur / Photographe"
  profilePicture = "images/profile.jpg"
  keywords = ""
  favicon = "favicons/"
  customCss = ["css/style.css", "css/custom.css"]
  customJs = []
  mainSections = ["posts"]
  # images = ["images/site-feature-image.png"]
  # Google Site Verification
  #googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
  enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
  use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://de.linkedin.com/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/victorprouff/"

  [[params.socialIcons]]
  icon = "fa-instagram"
  title = "instagram"
  url = "https://www.instagram.com/"

  [[params.socialIcons]]
  icon = "fa-envelope"
  title = "e-mail"
  url = "mailto:contact@victorprouff.fr"

## Menu items
[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
